exclude: ^(welcome/|path_finder/|semaphores/|car_system/)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
    files: \.(yaml|yml)$
    args: [--allow-multiple-documents]
  - id: end-of-file-fixer
    files: \.(c|cc|cpp|cxx|h|hpp|hxx)$
  - id: trailing-whitespace
    files: \.(c|cc|cpp|cxx|h|hpp|hxx)$
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v22.1.5'
  hooks:
  - id: clang-format
    files: \.(c|cc|cpp|cxx|h|hpp|hxx)$
- repo: local
  hooks:
  - id: copyright
    name: Check copyright
    entry: python deps/zpp_lib/scripts/check_copyright.py
    language: system
    pass_filenames: true
    files: \.(c|cc|cpp|cxx|h|hpp|hxx)$
- repo: local
  hooks:
  - id: clang-tidy-blinky
    name: clang-tidy-blinky
    entry: python deps/zpp_lib/scripts/run_clang_tidy.py --app blinky --board "nrf5340dk/nrf5340/cpuapp" --shield "adafruit_2_8_tft_touch_v2" --configs "log+debug+gpio" --wd "." --header-root blinky
    language: system
    pass_filenames: true
    require_serial: true
    files: ^(blinky)/.*\.(c|cc|cpp|cxx)$
  - id: clang-tidy-bme280
    name: clang-tidy-bme280
    entry: python deps/zpp_lib/scripts/run_clang_tidy.py --app bme280 --board "nrf5340dk/nrf5340/cpuapp" --shield "adafruit_2_8_tft_touch_v2" --configs "log+debug+sensor" --wd "." --header-root bme280
    language: system
    pass_filenames: true
    require_serial: true
    files: ^(bme280)/.*\.(c|cc|cpp|cxx)$
  - id: clang-tidy-sanitize
    name: clang-tidy-sanitize
    entry: python deps/zpp_lib/scripts/run_clang_tidy.py --app sanitize --board "nrf5340dk/nrf5340/cpuapp" --shield "adafruit_2_8_tft_touch_v2" --configs "log+debug+shell+san" --wd "." --header-root sanitize
    language: system
    pass_filenames: true
    require_serial: true
    files: ^(sanitize)/.*\.(c|cc|cpp|cxx)$
