name: Test AES workspace

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-apps:
    uses: AdvEmbSof/common-workflows/.github/workflows/build-zephyr-apps.yml@main
    secrets:
      personal_access_token: ${{ secrets.ADVEMBSOF_2026_2027 }}
    with:
      configuration_file: 'ci/applications_for_build.yaml'

  test-apps:
    uses: AdvEmbSof/common-workflows/.github/workflows/twister-tests.yml@main
    secrets:
      personal_access_token: ${{ secrets.ADVEMBSOF_2026_2027 }}
    with:
      configuration_file: 'ci/applications_for_test.yaml'
    permissions:
      checks: write
      pull-requests: write
      contents: read
